Make shutdown timeout configurable
gomods/athens pull request #1806
Opened 2022-11-30 22:22 UTC by jorng

## What is the problem I am trying to address?

Currently, when shutting down the server (via `SIGINT`), the shutdown closes any open connections after only 10 seconds (via a `context.WithTimeout`). This does not provie a lot of time for longer operations, such as listing versions, or downloading a larger module zip file.

When running in Kubernetes, and scaling instances or changing config, this causes a lot of dropped connections and gateway errors. 10 seconds is arguably much too short, and should be configurable.

## How is the fix applied?

This commit increases that default to 60 seconds, and adds a config variable to allow users to specify their desired timeout.

2023-01-19 07:00 UTC, nrwiersma approved these changes

2023-01-19 07:14 UTC, nrwiersma commented
You obviously need up fix the failing test.

2023-01-19 07:35 UTC, nrwiersma requested changes
Just realised you have not updated a test. Could you also rebase the PR please.

2023-01-23 17:14 UTC, jorng commented
Rebased and fixed the failing test.

2023-01-24 05:55 UTC, nrwiersma approved these changes
LGTM 🎉

2023-01-24 06:02 UTC, manugupt1 approved these changes

2023-01-24 06:02 UTC, manugupt1 commented
thanks!

2023-01-24 06:02 UTC, merged