Set up and use logrus logger in main
gomods/athens pull request #1819
Opened 2023-01-27 21:36 UTC by mikesep

## What is the problem I am trying to address?

Similar to #1817, this is part of an effort to get as much logging as possible to be consistently formatted by using the same (logrus) logger.

## How is the fix applied?

This PR sets up and use logrus logger as early as possible in `main`.
It also updates functions called by `main` to return errors more consistently.

I did change some of the logging text strings to the style I personally prefer, but they're not critical to this PR, and we can revert them as needed.

## What GitHub issue(s) does this PR fix or close?

None.

2023-01-27 22:36 UTC, mikesep commented
Works fine when testing locally, but I'm not seeing any log output on my cluster-based testing. Marking as draft until I figure out what's going on.

2023-01-31 15:29 UTC, mikesep commented
> I'm not seeing any log output in my cluster-based tests

This was mostly unrelated to the changes in this PR, as I'd hoped/suspected. (Details: I happen to be post-processing Athens's logs using `sed`, which seems to be doing more buffering now than before. Adding `--unbuffered` fixed the issue for me.)

Anyway, this PR should be good to go from what I can tell -- it's working correctly on my cluster so far.

2023-02-08 06:05 UTC, nrwiersma requested changes

2023-02-08 06:05 UTC, nrwiersma commented on cmd/proxy/actions/app.go
> +			return nil, fmt.Errorf("netrcFromToken error: %w", err)
```suggestion
			return nil, fmt.Errorf("creating .netrc from github token: %w", err)
```
Users will see these errors via the logger. Just mentioning the function is not generally helpful, as users dont know what that is.
As a bonus, consider that the log that is seen with be `Could not create app` or something like that, so it does not really need the error to also start with `could not`.

2023-02-10 16:21 UTC, mikesep commented on cmd/proxy/actions/app.go
> +func App(logger *log.Logger, conf *config.Config) (http.Handler, error) {
Hi @nrwiersma, I'm happy to follow conventions, but I hadn't found what you're mentioning in this project. In my last PR (#1817), I added logger params at the beginning. `addProxyRoutes` puts it in the middle: https://github.com/gomods/athens/blob/dbe3b5d1457feb2a8e4baa952e787538fc5aaa56/cmd/proxy/actions/app_proxy.go#L28-L33

2023-02-10 17:02 UTC, nrwiersma commented on cmd/proxy/actions/app.go
> +func App(logger *log.Logger, conf *config.Config) (http.Handler, error) {
Fair point.

2023-02-27 15:58 UTC, mikesep commented
Sorry for the delay here -- hoping to get back to this this week.

2023-12-08 14:26 UTC, DrPsychick commented
> Sorry for the delay here -- hoping to get back to this this week.

Hey @mikesep, any change you can get back to this?

2023-12-21 13:26 UTC, Ullaakut commented
Actually now conflicts with #1890 so we should either go all in with Logrus and uniformize it across the whole code base or make another PR and replace it with slog if it seems like a better alternative and worth the trouble of switching completely.

2024-01-02 15:19 UTC, mikesep commented
> > Sorry for the delay here -- hoping to get back to this this week.
> 
> Hey @mikesep, any [chance] you can get back to this?

Hi folks, sorry the lack of progress here. I'm rereading what I did here and how logging is still used in the `main` branch to get back up to speed.

> Actually now conflicts with #1890 so we should either go all in with Logrus and uniformize it across the whole code base or make another PR and replace it with slog if it seems like a better alternative and worth the trouble of switching completely.

I think the conservative approach is to lean towards finishing up this PR before considering the merits and costs of moving to [`slog`](https://pkg.go.dev/log/slog) and/or redesigning how Athens uses its `pkg/log` and `pkg/errors` packages.

2024-01-03 09:36 UTC, nrwiersma approved these changes
LGTM

2024-01-04 09:51 UTC, Ullaakut approved these changes

2024-01-04 10:11 UTC, merged

2024-01-04 15:27 UTC, mikesep commented
Thanks for the reviews and for reminding me to get back to this! Sorry again for taking so long!