feat: Publish multi-arch docker image (amd64 and arm64)
gomods/athens pull request #1862
Opened 2023-03-24 09:34 UTC by project0

## What is the problem I am trying to address?

We want to switch our workload to arm64 (AWS Graviton) for improved cost-efficiency. One of the remaining images not proving arm64 compatible images is athens.

This PR supersede #1794 as the pipeline was moved to github actions

## How is the fix applied?

extend github actions workflow

## What GitHub issue(s) does this PR fix or close?

Fixes #

2023-04-01 18:43 UTC, DrPsychick commented
@project0 We'll take a look at this after the 0.12.0 version is released.

2023-04-21 07:20 UTC, mloiseleur commented
Hello @DrPsychick ,

 0.12.0 version has been released. Is the path clear to review this PR, now ?

2023-04-21 20:26 UTC, DrPsychick commented
Hey @mloiseleur, generally yes, we're on track now again the latest Athens.
Next up will be 0.12.1 with bugfixes (soon). I will take a look at this within the next 2 weeks.

2023-05-02 22:26 UTC, DrPsychick requested changes

2023-05-03 06:43 UTC, project0 commented on cmd/proxy/Dockerfile
> +		TARGETARCH
No, someone kicked of the file with tabs, but i can change format to white spaces

2023-05-03 10:40 UTC, DrPsychick requested changes
How did you test this?

I cannot get it to run through on my fork, so please test it in your fork so that the actions actually run through.

Also, one minor thing: all other workflows use `.yml` extension, so keep it consistent please.

https://github.com/DrPsychick/athens/actions/runs/4869859787/jobs/8684877269

2023-05-03 12:45 UTC, project0 commented
@DrPsychick i am sorry, i should have tested it better. There seem to be some issues with re-usables here, so i decided to avoid them at the end.

2023-05-03 19:03 UTC, DrPsychick requested changes
minor fix and we're good I think.

2023-05-03 22:40 UTC, justenwalker commented
Hey @project0 ; thanks for implementing this!

Perhaps we could also get arm64 builds in the .goreleaser.yml as well?

https://github.com/gomods/athens/pull/1870/files#diff-42e26dc67aed8aa3edb2472b4403288c1699fb6dc47419b9a475f0f224fe4689

2023-05-04 07:04 UTC, DrPsychick approved these changes
Thank you for your contribution!

2023-05-04 07:11 UTC, merged