Updated link and format on the experimental public proxy
gomods/athens pull request #1864
Opened 2023-04-01 03:50 UTC by ColumbiaMancera

## What is the problem I am trying to address?

Issue with the documentation, I'm trying to fix a faulty link. 

On the section titled "More Details Please!" and specifically the sentence "There is currently an experimental public proxy (at https://athens.azurefd.net/) that you can use to try out Athens", whenever I try to access the page it gives me a blank page with the message "Welcome to The Athens Proxy". I'd currently change this message to "There is currently an [experimental public proxy](https://athens.azurefd.net/) in development that you can use to try out Athens...". I'd like to be assigned to this issue and I'll be submitting a PR to solve it.

## How is the fix applied?

I've adapted the text in the README.md to explain the experimental public proxy is a work in progress and also put a hyperlink over the text. 

## What GitHub issue(s) does this PR fix or close?

https://github.com/gomods/athens/issues/1863 

Fixes #

Fixes #1863

2023-04-01 05:23 UTC, nrwiersma requested changes
Discussing this in the issue before review.

2023-04-01 13:26 UTC, marwan-at-work requested changes
We should probably remove the entire paragraph because we don't have one anymore?

2023-05-10 02:55 UTC, ColumbiaMancera commented
> We should probably remove the entire paragraph because we don't have one anymore?

If there currently isn't one anymore and the docs are outdated, then I think we should probably remove it!

2023-05-11 23:31 UTC, DrPsychick approved these changes

2023-05-12 05:02 UTC, nrwiersma approved these changes

2023-12-08 14:18 UTC, merged