feat: support GitHub App authentication
gomods/athens pull request #1988
Opened 2024-10-01 12:01 UTC by nrwiersma

## What is the problem I am trying to address?

This adds support for GitHub App authentication using Git Credential Helpers.

## How is the fix applied?

The GHA Git Credential Helper is installed in the Docker image by default, and the process is documented.

2024-10-01 12:20 UTC, Ullaakut approved these changes
I assume 3500 is a typo? Only thing that seems wrong

2024-10-01 12:20 UTC, Ullaakut commented on docs/content/configuration/authentication.md
> +This instructs Git to authenticate with the GitHub App and cache the results for 3500s (the authentication token is valid for 1 hour).
```suggestion
This instructs Git to authenticate with the GitHub App and cache the results for 3600s (the authentication token is valid for 1 hour).
```

2024-10-02 02:36 UTC, matt0x6F requested changes
So, this only works for github.com. The application is leveraging [bradleyfalzon/ghinstallation](https://github.com/bradleyfalzon/ghinstallation/) which has a clear path for supporting both GHE and github.com. Can we PR, fork, or import in order to support both instead?

2024-10-02 04:41 UTC, nrwiersma commented
I am wondering if GHE support should be a second step for this? I would prefer to try upstream the GHE support first, before running a separate fork, and this can take time. 

Would glad make an Issue to keep track and a note in the docs about this.

2024-10-06 17:41 UTC, Ullaakut approved these changes

2024-10-21 18:06 UTC, matt0x6F approved these changes

2024-10-21 18:14 UTC, merged